[AssistedSpecification]
number_of_neighbors = 20
largest_neighborhood = 20
maximum_attempts = 100

[MonteCarlo]
number_of_draws = 250
seed = 0

[Estimation]
bootstrap_samples = 100
max_number_parameters_to_report = 15
save_iterations = "True"
maximum_number_catalog_expressions = 100
optimization_algorithm = "simple_bounds"

[Output]
identification_threshold = 1e-5
only_robust_stats = "True"
generate_html = "True"
generate_pickle = "True"

[MultiThreading]
number_of_threads = 0

[SimpleBounds]
second_derivatives = 1.0
tolerance = 6.06273418136464e-6
max_iterations = 100
infeasible_cg = "False"
initial_radius = 10
steptol = 1e-5
enlarging_factor = 10

[Specification]
missing_data = 99999

[TrustRegion]
dogleg = "True"
